services:
  client-gateway:
    build:
      context: ./client-gateway
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"

  orders-service:
    build:
      context: ./orders-service
    environment:
      - DATABASE_URL=postgresql://user:password@orders-db:5432/orders_db
    depends_on:
      - orders-db
    ports:
      - "5002:5002"

  orders-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db
    depends_on:
      - auth-db
    ports:
      - "5001:5001"

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
volumes:
  db_data:
  auth_db_data:
